# TODO add Debug and Releas to the matrix, and get deploy working, then remove the appveyor stuff.

name: Build Windows

on: 
  push:
  pull_request:

jobs:
  build: 
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86, x64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build x86
        run: |
                mkdir build
                cd build
                cmake -G "Visual Studio 17 2022" -A Win32 ..
                msbuild ALL_BUILD.vcxproj
        if: matrix.arch == 'x86'

      - name: Build x64
        run: |
                mkdir build
                cd build
                cmake -G "Visual Studio 17 2022" -A x64 ..
                msbuild ALL_BUILD.vcxproj
        if: matrix.arch == 'x64'

#       - name: Upload Artifacts
#         uses: actions/upload-artifact@v2
#         with: 
#           path: |
#             deploy/*

#       - name: Create Release
#         if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
#         uses: ncipollo/release-action@v1
#         with:
#             artifacts: "deploy/*"
#             token: ${{ secrets.GITHUB_TOKEN }}
#             allowUpdates: true
