
name: Build OpenPnP Capture Distribution for Windows

on: 
  push:
  pull_request:

jobs:
  build: 
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86, x64]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
                mkdir build && cd build && cmake -G "Visual Studio 17 2022" -A Win32 .. && make

#       - name: Upload Artifacts
#         uses: actions/upload-artifact@v2
#         with: 
#           path: |
#             deploy/*

#       - name: Create Release
#         if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
#         uses: ncipollo/release-action@v1
#         with:
#             artifacts: "deploy/*"
#             token: ${{ secrets.GITHUB_TOKEN }}
#             allowUpdates: true
